name: release

# Trigger on tags pushed to the repository
on:
    push:
        tags:
            - 'v*' # Push events to matching v*, i.e. v1.0.0, v20.15.10

permissions:
    contents: write
    # packages: write
    # issues: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Fetch all tags
                run: git fetch --force --tags

            -   name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version: 1.22
                    check-latest: true

            -   name: Test
                run: go test -v ./...

            -   name: Run GoReleaser
                uses: goreleaser/goreleaser-action@v5.0.0
                with:
                    # either 'goreleaser' (default) or 'goreleaser-pro'
                    distribution: goreleaser
                    version: latest
                    args: release --clean
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
                    # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}